name: Trigger auto deployment for abossard

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'frontend/nextjs-blog/**'
    - '.github/workflows/abossard-AutoDeployTrigger-e8acd15d-f5e6-4bd9-96da-e1def55c0f7e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: abossard.azurecr.io
          username: ${{ secrets.ABOSSARD_REGISTRY_USERNAME }}
          password: ${{ secrets.ABOSSARD_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: abossard.azurecr.io/nextjs_blog:${{ github.sha }}
          file: frontend/nextjs-blog/Dockerfile
          context: frontend/nextjs-blog/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ABOSSARD_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            #az containerapp registry set -n abossard -g blogggggggg --server abossard.azurecr.io --identity system
            az containerapp update -n abossard -g blogggggggg --image abossard.azurecr.io/nextjs_blog:${{ github.sha }}
